export default {
  strings: {
    heading_text: 'Note App',
    placehoder_text: 'Enter your Notes Here...',
    error_text: 'Error: Input field is empty...',
    helping_text: 'No Notes available',
    sub_title: 'Your Note:',
    splash_text: 'Navigation',
    add_note: 'Note App',
    edit_note: 'Edit Note',
    go_back: 'Go Back',
    scr_heading: 'NoteDetailScreen',
    welcome_back: 'Welcome Back!!',
    welcome: 'Welcome!!',
    login: 'Login',
    dont_account: "Don't have an account?",
    forgot_password: 'Forgot Password?',
    success_login: 'You have successfully Login!!',
    register: 'Register',
    note_title: 'Note App',
  },
  fonts: {
    ROBOTO_BLACK: 'Roboto-Black',
    ROBOTO_LIGHT: 'Roboto-Light',
    ROBOTO_BOLD: 'Roboto-Bold',
    Oswald: 'Oswald-VariableFont_wght',
    PRIMARY_BOLD: 'NunitoSans-Bold',
    PRIMARY_REGULAR: 'NunitoSans-Regular',
    PRIMARY_SEMIBOLD: 'NunitoSans-SemiBold',
    PRIMARY_ITALIC: 'NunitoSans-Italic',
    PRIMARY_LIGHT: 'NunitoSans-Light',
    SECONDARY_BOLD: 'MontSerrat-Bold',
  },
};
